# Generated by Django 5.1.2 on 2024-10-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_rename_numero_de_celular_estudante_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nome',
        ),
    ]
