# Generated by Django 5.1.2 on 2024-10-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='numero_de_celular',
            new_name='celular',
        ),
    ]
